### ISSUE TITLE
About DistributedDataParallel

### ISSUE THREAD

**Issue by gufan-d** [JayQine/MGD-SSSS#2]
hi!When I train MGD,I notice that the first GPU run more processes.It seems that dataloader does not use DistributedDataParallel.Am I right?

"""
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     45545      C   ...onda/envs/mgd/bin/python3     5685MiB |
|    0   N/A  N/A     45546      C   ...onda/envs/mgd/bin/python3     1301MiB |
|    0   N/A  N/A     45547      C   ...onda/envs/mgd/bin/python3     1301MiB |
|    0   N/A  N/A     45548      C   ...onda/envs/mgd/bin/python3     1301MiB |
|    1   N/A  N/A     45546      C   ...onda/envs/mgd/bin/python3     5739MiB |
|    2   N/A  N/A     45547      C   ...onda/envs/mgd/bin/python3     5739MiB |
|    3   N/A  N/A     45548      C   ...onda/envs/mgd/bin/python3     5719MiB 
"""

**Comment by JieQin-AI** [comment]
Yes, there will be some imbalances. We put some of the additional calculations on GPU0, but DDP is indeed used when processing training data.
