### ISSUE TITLE
About Param and FLOPs

### ISSUE THREAD

**Issue by gufan-d** [JayQine/MGD-SSSS#3]
Sorry to bother you.
Param and FLOPs in Table 1 of your paper are 11.19M and 17.20G which backbone is resnet18.But when I calculate the params with torchstat(inputsize=(3, 512, 512)),it's16.62M and 42.51GFlops.
The output is as follows:
`
 module name   input shape  output shape      params memory(MB)              MAdd             Flops  MemRead(B)  MemWrite(B) duration[%]    MemR+W(B)
0                     branch1.backbone.conv1.0     3 512 512    32 256 256       864.0       8.00     111,149,056.0      56,623,104.0   3149184.0    8388608.0       0.28%   11537792.0
1                     branch1.backbone.conv1.1    32 256 256    32 256 256        64.0       8.00               0.0               0.0         0.0          0.0       0.08%          0.0
....
....
86                      branch2.backbone.conv1     0   0   0     0   0   0         0.0       0.00               0.0               0.0         0.0          0.0       0.00%          0.0
....
....
266                   branch3.backbone.conv1.0     0   0   0     0   0   0         0.0       0.00               0.0               0.0         0.0          0.0       0.00%          0.0
....
....

Total params: 16,627,413

Total memory: 335.32MB
Total MAdd: 84.95GMAdd
Total Flops: 42.51GFlops
Total MemR+W: 536.69MB

`

**Comment by JieQin-AI** [comment]
You may need to check whether you are only calculating the parameters of the backbone part.
