### ISSUE TITLE
关于代码中optimizer_3的疑问

### ISSUE THREAD

**Issue by precious-dust** [JayQine/MGD-SSSS#5]
作者，您好！

我是一名深度学习和计算机视觉的初学者，在拜读了您的论文之后，感觉这个工作相当出色、想以此作为我的基准。
但是在分析代码的时候，我有一些疑问，具体如下：

- 如定义了optimizer_3但是没有用过；
- 而且在论文中提到 “按照CPS [7] 对两个教师模型进行预训练，并冻结它们的参数，进行离线蒸馏程序以精炼学生模型。” 那么我想老师1和老师2是不用更新参数的。

我的疑问也添加在截图中，如果您有时间请帮我解答一下，这对我非常重要！
![Snipaste_2024-07-05_16-27-01](https://github.com/JayQine/MGD-SSSS/assets/34473047/34e213e5-05b0-4a46-bdd4-5a3c8f489d05)
![Snipaste_2024-07-05_16-37-03](https://github.com/JayQine/MGD-SSSS/assets/34473047/f1735cf4-bd51-4e6e-b66c-c68e848e267f)
![Snipaste_2024-07-05_16-38-59](https://github.com/JayQine/MGD-SSSS/assets/34473047/046bd5ef-a077-46b6-95c0-194e43b00545)
![Snipaste_2024-07-05_16-30-34](https://github.com/JayQine/MGD-SSSS/assets/34473047/0273ef6b-12cb-4d31-b4a8-0a2f2cd8c26c)
。
在此特别感谢您！最后祝愿您工作顺利，学术常青~

**Comment by JieQin-AI** [comment]
研究者，您好：

感谢您对我们工作的认可，以及对代码问题的指出。

关于代码中的相关问题，其中optimizer_r和optimizer_3都是冗余的设置，它们在上传代码过程中忘记去除了。两个教师模型的参数都被固定住了，所以实际训练更新过程中不会对他们的参数造成影响。希望能够回答到您的问题。

**Comment by precious-dust** [comment]
好的，我明白了老师。感谢您的耐心答复~


Xupt_Hqz
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JayQine/MGD-SSSS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月17日(星期三) 晚上10:23
***@***.***&gt;;
抄送:&nbsp;"Precious ***@***.******@***.***&gt;;
主题:&nbsp;Re: [JayQine/MGD-SSSS] 关于代码中optimizer_3的疑问 (Issue #5)





 
研究者，您好：
 
感谢您对我们工作的认可，以及对代码问题的指出。
 
关于代码中的相关问题，其中optimizer_r和optimizer_3都是冗余的设置，它们在上传代码过程中忘记去除了。两个教师模型的参数都被固定住了，所以实际训练更新过程中不会对他们的参数造成影响。希望能够回答到您的问题。
