### ISSUE TITLE
关于复现精度的问题

### ISSUE THREAD

**Issue by precious-dust** [JayQine/MGD-SSSS#6]
老师，您好！

在VOC-1/16和VOC-1/8的数据量下，我的复现结果与原论文很接近。
但是，在VOC-1/4和VOC-1/2的数据量下，却有种相差甚远的感觉，我将展示我的复现结果，很疑惑是不是还有什么调参技巧，望您赐教。

注：我的环境是2张24G的显卡，epochs我一般设置的默认的34，lr==0.005、bs==16.
![Snipaste_2024-07-22_15-50-23](https://github.com/user-attachments/assets/639c775f-f15a-4f02-945d-6b5e20b6d8ad)
![Snipaste_2024-07-22_15-41-11](https://github.com/user-attachments/assets/8695fcca-b81d-4c9b-94cd-f55a8b35006f)

**Comment by precious-dust** [comment]
当我调大了epochs，在P6000双卡上跑VOC-2，得到了71.86的meanIOU成绩，甚至比原论文的71.59还要高一些呢；
在P40双卡上，我按照上述的配置，得到的精度也高于论文...

**Comment by precious-dust** [comment]
老师，我突然想起来，City上的复现结果与论文差距较大，我想知道该如何调整以接近论文的meanIOU，继续调大epochs吗？
![Snipaste_2024-07-30_09-38-12](https://github.com/user-attachments/assets/de0fd8cf-8790-44b4-9b7b-e11aa93e2ebf)

**Comment by JieQin-AI** [comment]
训练细节问题方便的话请通过邮箱沟通，qinjie2019@ia.ac.cn
